project:
  type: website
  resources:
    - old_resume.pdf
    - Team_DW.pdf
    - Predicting Obesity Status.pdf
    - Analyzing Tire Degradation.pdf
    - BSA Tennis Report.pdf


website:
  title: "Cameryn Harvey"
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: projects.qmd
        text: projects
    background: "#ccdcc3"
 

  page-footer:
    right: "&copy; 2025, Cameryn Harvey"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    

execute: 
  freeze: auto

